language: php

php: 7.3

install:
    - composer install $COMPOSER_FLAGS

script:
    # run tests for tested posts (with "tested: true" in header configuration)
    - vendor/bin/phpunit --coverage-clover coverage.xml

    # check code standard (defined in composer.json "scripts" section)
    - composer check-cs
    - composer phpstan

    # test that website is generated
    - vendor/bin/statie generate source

    # tweets posts
    - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then vendor/bin/statie tweet-post; fi

after_script:
    # upload coverage
    - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - php coveralls.phar --verbose --config tests/.coveralls.yml

# see https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: output
    on:
        branch: master

# do not send success notifications, they have no value
notifications:
    email:
        on_success: never
