language: php

matrix:
    include:
        - php: 7.1
          env: STATIC_ANALYSIS=1
        - php: 7.2
          env: PHPUNIT_FLAGS="--coverage-clover coverage.xml"

install:
    - composer install

script:
    # run tests for tested posts (with "tested: true" in header configuration)
    - vendor/bin/phpunit $PHPUNIT_FLAGS
    # check code standard (defined in composer.json "scripts" section)
    - if [[ $STATIC_ANALYSIS = 1 ]]; then composer check-cs; fi
    - if [[ $STATIC_ANALYSIS = 1 ]]; then composer phpstan; fi
    # test that website is generated
    - vendor/bin/statie generate source

after_script:
    - |
        if [ "$PHPUNIT_FLAGS" != "" ]; then
            wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
            php coveralls.phar --verbose --config tests/.coveralls.yml
        fi

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: output
    on:
        branch: master

# do not send success notifications, they have no value
notifications:
    email:
        on_success: never
